---
- name: Extract jdk8u212-b03.zip into /usr/local/vodafone/jdk8u292-b10/
  ansible.builtin.unarchive:
    src: /home/kunal/ansible-bootstrap/resources/java/jdk8u292-b10.tar.gz
    dest: /usr/local/vodafone/
    group: kunal
    owner: kunal
  when: ansible_facts['os_family'] == "Debian"
  register: javaExtract

- name: Create a symbolic link for java8 to jdk8
  ansible.builtin.file:
    src: /usr/local/vodafone/jdk8u292-b10/
    dest: /usr/local/vodafone/java8
    owner: kunal
    group: kunal
    state: link
  when: javaExtract.changed

...
